### PR TITLE
STOR-1160: Rebase to v1.28.0 for OCP 4.14

### PR DESCRIPTION
**Pull request by RomanBednar**
Diff to upstream v1.25.1:
https://github.com/kubernetes-sigs/azurefile-csi-driver/compare/v1.28.0...RomanBednar:rebase-v1.28.0

Notable upstream features since v1.25.1 (OCP 4.13):

- Support workload identity by @cvvz in https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/1193
- append help link when there is mount error by @andyzhangx in https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/1179
- add selectRandomMatchingAccount parameter in storage class by @andyzhangx in https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/1225
-  enable securityContext.seccompProfile by @andyzhangx in https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/1210

cc @openshift/storage

### CODE REVIEW

**Comment by jsafrane** [comment]
I think the unit test is confused by running in a Kubernetes cluster - it constructs a Kubernetes client from `/var/run/secrets/kubernetes.io/serviceaccount/token`:

https://github.com/openshift/azure-file-csi-driver/blob/817a13bf2d4d1c6d70d0ae9169200c7bf2e82f0c/vendor/k8s.io/client-go/tools/clientcmd/client_config.go#L604-L609

It looks like https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/1182/ has broken it. IMO, the tests should not set `KUBERNETES_SERVICE_HOST` / `KUBERNETES_SERVICE_PORT`. Can you please fix it upstream?

**Comment by RomanBednar** [comment]
Cherry-picked https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/1294 from upstream, CI should be ok now.

/unhold

**Comment by duanwei33** [comment]
QE checked the pre-submit CI all passed and the coverage looks good.

**Pull request merged**
