### PR TITLE
Bug 2019128: Merge changes from upstream tag v1.7.0 into master

### PR DESCRIPTION
**Pull request by bertinatto**
https://github.com/kubernetes-sigs/azurefile-csi-driver/compare/v1.7.0...bertinatto:merge-v1.7.0

CC @openshift/storage

### CODE REVIEW

**Comment by jsafrane** [comment]
Looks good, but why the unit test fail? I see PASS everywhere, am I blind?
/retest

**Comment by bertinatto** [comment]
/test all
to make sure unit tests won't fail

**Pull request merged**
