### PR TITLE
STOR-1390: Rebase v1.29.2 for OCP 4.15

### PR DESCRIPTION
**Pull request by RomanBednar**
Diff to upstream v1.29.2:
https://github.com/kubernetes-sigs/azurefile-csi-driver/compare/v1.29.2...RomanBednar:azure-file-csi-driver:rebase-v1.29.2

Upstream changelog since v1.28.1 (OCP 4.14):
https://github.com/kubernetes-sigs/azurefile-csi-driver/releases/tag/v1.28.2
https://github.com/kubernetes-sigs/azurefile-csi-driver/releases/tag/v1.28.3
https://github.com/kubernetes-sigs/azurefile-csi-driver/releases/tag/v1.28.4
https://github.com/kubernetes-sigs/azurefile-csi-driver/releases/tag/v1.28.5
https://github.com/kubernetes-sigs/azurefile-csi-driver/releases/tag/v1.29.0
https://github.com/kubernetes-sigs/azurefile-csi-driver/releases/tag/v1.29.1
https://github.com/kubernetes-sigs/azurefile-csi-driver/releases/tag/v1.29.2

@openshift/storage

### CODE REVIEW

**Comment by RomanBednar** [comment]
/unhold

Adding a carry patch to stay at golang 1.20 for this rebase. Bump to 1.21 is planned for ocp 4.16.

**Comment by duanwei33** [comment]
Manually test the extended case, looks good.
/label qe-approved

**Pull request merged**
