### PR TITLE
STOR-1586: Rebase v1.29.3

### PR DESCRIPTION
**Pull request by gnufied**
This PR uses `git merge -s ours` strategy for creating the rebase.

https://github.com/kubernetes-sigs/azurefile-csi-driver/compare/v1.29.3...gnufied:azure-file-csi-driver:rebase-v1.29.3

### CODE REVIEW

**Comment by gnufied** [comment]
Failures in nfs-csi looks unrelated.

/retest

**Comment by duanwei33** [comment]
QE is working on pre-merge test.

**Comment by RomanBednar** [comment]
@gnufied For other rebases I amended the .snyk file to a single [commit](https://github.com/openshift/aws-ebs-csi-driver/pull/257/commits/9c49664b6203a41bc0d20119d3194fb8f60cf007#diff-45f12c395c9d92360df0720e2b2503c35b68af15bc53c5f5cd5b8ebfa763163f) - the one that adds openshift files: `UPSTREAM: <carry>: Add OpenShift files`

Wouldn't it be better to do it here too and reduce the amount of carries?

**Comment by gnufied** [comment]
@RomanBednar sure.  I can do that.

**Comment by duanwei33** [comment]
I hit the similar issue in pre-merge testing, the azure-file-csi-driver image build failed sometimes, and I got a successful job after several trying.

**Comment by duanwei33** [comment]
Manually tested the customer-facing feature looks good, and I launched e2e test manually, it got passed. 
/label qe-approved

**Comment by jsafrane** [comment]
/retest
after https://github.com/openshift/release/pull/48370

**Pull request merged**
