### PR TITLE
STOR-1604: Rebase v1.30.3 for OCP 4.17

### PR DESCRIPTION
**Pull request by RomanBednar**
Diff to upstream v1.30.3:
https://github.com/kubernetes-sigs/azurefile-csi-driver/compare/v1.30.3...RomanBednar:azure-file-csi-driver:rebase-v1.30.3

Full changelog: https://github.com/kubernetes-sigs/azurefile-csi-driver/releases/tag/v1.30.3

@openshift/storage

### CODE REVIEW

**Comment by RomanBednar** [comment]
/assign @duanwei33

Needs QE approval.

**Comment by duanwei33** [comment]
@radeore Please help take this rebase test.

**Comment by jsafrane** [comment]
The main upstream changelog is https://github.com/kubernetes-sigs/azurefile-csi-driver/releases/tag/v1.30.0

**Pull request merged**
